### ISSUE TITLE
Jobs failing with 1.1.0 with job.uses from same repository 

### ISSUE THREAD

**Issue by kuhnroyal** [zgosalvez/github-actions-ensure-sha-pinned-actions#13]
I am using actions from the same repository which should not be required to be pinned.

This was previously working and is now failing with 1.1.0.

```yaml
      - name: Foo
        id: foo
        uses: ./.github/actions/foo
```
