### ISSUE TITLE
Jobs with multiple steps will not fail if the last step is pinned

### ISSUE THREAD

**Issue by wadells** [zgosalvez/github-actions-ensure-sha-pinned-actions#133]
When a workflow has both pinned and unpinned steps, only the status of the final step is used to determine if the overall job should pass or fail. Consider the following workflow:
```
on:
  push:

name: Continuous Integration

jobs:
  check-github-actions:
    name: Check GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@b35f285b9bb7e80de0967367cee66d3b6d50ceca # v3.0.1
```

This will pass because `zgosalvez/github-actions-ensure-sha-pinned-actions` is pinned (and the last step), whereas the earlier `actions/checkout` should cause the job to fail.

Tested using v3.0.1.
