### ISSUE TITLE
Workflow file with multiple uses only shows first failure

### ISSUE THREAD

**Issue by leemeador** [zgosalvez/github-actions-ensure-sha-pinned-actions#162]
Using this version:

```
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@v3.0.7
```

With these lines in among the steps of a workflow in .github/workflows

```yaml
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

    ... more stuff here without any 'uses" steps ...

      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
```

shows this error:

```text
.github/workflows/the-workflow.yaml
  Error:  jitterbit/get-changed-files@v1 is not pinned to a full length commit SHA.
```

And there is no mention of the checkout without a sha
