### ISSUE TITLE
Feature Request - Optional Warning (or dry run) instead of an error

### ISSUE THREAD

**Issue by vikas027** [zgosalvez/github-actions-ensure-sha-pinned-actions#18]
Some organizations use a lot of GitHub Actions and to make sure the transition is smooth and non-blocking, it will good to have warning instead of errors.

Something like this will be good.
```yaml
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@v1.0.1 # Replace this
        with:
          dry_run: true (can be false by default)
          allowlist: |
            aws-actions/
            docker/login-action
```
