### ISSUE TITLE
Incorrect handling of local jobs.

### ISSUE THREAD

**Issue by TGWolf** [zgosalvez/github-actions-ensure-sha-pinned-actions#83]
This is a valid action syntax:

```
jobs:
  pinned_actions:
    uses: ./.github/workflows/reusable-pinned-actions.yml

```
But the action throws a warning saying there are no steps or uses

**Comment by MPV** [comment]
@zgosalvez I can confirm this issue.

What would be needed to solve it?

**Comment by MPV** [comment]
This is the line giving the warning:
https://github.com/zgosalvez/github-actions-ensure-sha-pinned-actions/blob/f32435541e24cd6a4700a7f52bb2ec59e80603b1/src/index.js#L54

Though I haven't yet understood why it's not arriving at any of the lines that print this warning/error instead:
`${uses} is not pinned to a full length commit SHA.`

Any ideas how we resolve this?

**Comment by MPV** [comment]
I also tried using the `allowlist` for this, but didn't get the following to work as a workaround either (still getting the same warnings):

```
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@v2
        with:
          allowlist: |
            ./
```
